[package]
name = "linked-data-core"
description = "Core library for Linked Data crates"
homepage = "https://github.com/luminvent/linked-data-core"
repository = "https://github.com/luminvent/linked-data-core"
version = "0.2.2"
edition = "2024"
license = "MIT"

[dependencies]
oxiri = { version = "0.3", features = ["serde"] }
proc-macro-error3 = "3.1.1"
proc-macro2 = "1.0.107"
quote = "1.0.47"
snafu = "0.9.2"
syn = { version = "3.0.6", features = ["visit", "extra-traits"] }
